name: Sauce Labs Android

on:
  workflow_call:
    secrets:
      DEVOPS_LOGIN_TOKEN:
        description: 'Token of the DevOps Account'
        required: true
      SAUCE_LABS_ACCESS_KEY:
        description: 'Sauce Labs Access Key'
        required: true
      JARBIS_TOKEN:
        description: 'Jarbis Token'
        required: true
    inputs:
      PROJECT_NAME:
        type: string
        description: 'Name of the Project to Build App'
        required: true

jobs:
  test:
    name:  Android Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Clone Template Appium APP
        run: git clone "https://${{ secrets.DEVOPS_LOGIN_TOKEN }}:x-oauth-basic@github.com/platformbuilders/${{ inputs.PROJECT_NAME }}.git"

      - name: Upload File to the Saucelabs
        run: |
          ID_SAUCELABS=$(curl -u "qabuilders:${{ secrets.SAUCE_LABS_ACCESS_KEY }}" --location \
          --request POST 'https://api.us-west-1.saucelabs.com/v1/storage/upload' \
          --form 'payload=@"template-appium-app/Android/app-release.apk"' \
          --form 'name="app-release.apk"' | jq '.item.id') 
          echo "ID_SAUCELABS=$ID_SAUCELABS" >> $GITHUB_ENV

      - name: Clone Template Appium
        run: git clone "https://${{ secrets.DEVOPS_LOGIN_TOKEN }}:x-oauth-basic@github.com/platformbuilders/template-appium.git"

      - name: Build and Test
        run: |
          cd template-appium
          ls -lah
          yarn install
          yarn run sauce:android:build
        env:
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_LABS_ACCESS_KEY }}
          ID_SAUCELABS: ${{ env.SAUCE_LABS_ID }}

      - name: Slack Notification - failure
        if: ${{ failure() }}
        run: |
          cd template-appium
          ls -lah
          pwd
          ls reports/html-reports/screenshots/
          curl -F file=@reports/html-reports/screenshots/TesteFalhou.png -F "initial_comment=:android: Android - Teste Falhou :x: :sob:" -F channels=C012TP9BAB1 -H "Authorization: Bearer ${{ secrets.JARBIS_TOKEN }}" https://slack.com/api/files.upload

      - name: Slack Message
        if: ${{ success() }}
        run: |
          cd template-appium
          ls -lah
          pwd
          ls reports/html-reports/screenshots/
          curl -F file=@reports/html-reports/screenshots/TelaInicial.png -F "initial_comment=:android: Android - Teste Realizado com Sucesso :white_check_mark: :rocket:" -F channels=C012TP9BAB1 -H "Authorization: Bearer ${{ secrets.JARBIS_TOKEN }}" https://slack.com/api/files.upload

      - name: Archive result test
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: report test
          path: template-appium/reports/
