name: SonarQube Analysis

on:
  workflow_call:
    inputs:
      SONAR_SOURCE_PATH:
        description: 'Caminho do código-fonte para análise'
        required: false
        default: '.'
        type: string
      SONAR_PROJECT_KEY:
        description: 'Nome do projeto no sonar'
        required: false
        default: '.'
        type: string
    secrets:
      SONAR_TOKEN:
        description: 'Token de autenticação para o SonarQube'
        required: true
      SONAR_HOST_URL:
        description: 'URL do servidor SonarQube'
        required: true

jobs:
  front_scan:
    name: SonarQube Front Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - name: SonarQube Scan 
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          projectBaseDir: ${{ inputs.SONAR_SOURCE_PATH }}
          args: >
            -Dsonar.projectKey=${{ inputs.SONAR_PROJECT_KEY }}
            -Dsonar.exclusions=**/*.java
  
  check_java:
    name: Check for Java files
    runs-on: ubuntu-latest
    outputs:
      has_java: ${{ steps.check.outputs.has_java }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check if Java files exist
        id: check
        run: |
          if find . -name "*.java" | grep -q .; then
            echo "has_java=true" >> $GITHUB_OUTPUT
          else
            echo "has_java=false" >> $GITHUB_OUTPUT
          fi


  backend_scan:
    name: Backend SonarQube Analysis
    runs-on: ubuntu-latest
    needs: check_java
    if: ${{ needs.check_java.outputs.has_java == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Sonar Scanner
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner.zip -d $HOME
          export PATH="$HOME/sonar-scanner-5.0.1.3006-linux/bin:$PATH"

      - name: Build Java Project
        run: |
          if [ -f "build.gradle" ]; then
            ./gradlew build
          elif [ -f "pom.xml" ]; then
            ./mvnw clean install
          else
            echo "Nenhum arquivo de build encontrado, pulando build."
          fi

      - name: Backend SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=${{ inputs.SONAR_PROJECT_KEY }}-java \
            -Dsonar.sources=${{ inputs.SONAR_SOURCE_PATH }} \
            -Dsonar.language=java \
            -Dsonar.java.binaries=build/classes/java

